update states set state_name_k='ಕರ್ನಾಟಕ' where id=1;
update states set state_name_k='ವಿಜಯಪುರ' where id=2;
update states set state_name_k='ವಿಜಯಪುರ ' where id=3;
update states set state_name_k='ಇಂಡಿ' where id=4;
update states set state_name_k='ಸಿಂದಗಿ' where id=5;
update states set state_name_k='ಬಸವನ ಬಾಗೇವಾಡಿ' where id=6;
update states set state_name_k='ಮುದ್ದೇಬಿಹಾಳ' where id=7;
update states set state_name_k='ತಿಕೋಟಾ' where id=8;
update states set state_name_k='ಬಬಲೇಶ್ವರ' where id=9;
update states set state_name_k='ಮಮದಾಪೂರ' where id=10;
update states set state_name_k='ನಾಗಠಾಣ' where id=11;
update states set state_name_k='ಕ. ವಿಜಯಪುರ' where id=12;
update states set state_name_k='ವಿಜಯಪುರ' where id=13;
update states set state_name_k='ಬಬಲೇಶ್ವರ' where id=14;
update states set state_name_k='ನಾಗಠಾಣ' where id=15;
update states set state_name_k='ತಿಕೋಟಾ' where id=16;
update states set state_name_k='ತೊರವಿ' where id=17;
update states set state_name_k='ನವರಸಪುರ' where id=18;
update states set state_name_k='ತಾಜಪುರ H.' where id=19;
update states set state_name_k='ಕೋಟ್ಯಾಳ' where id=20;
update states set state_name_k='ಹೊನವಾಡ' where id=21;
update states set state_name_k='ಕನಮಡಿ' where id=22;
update states set state_name_k='ಬಿಜ್ಜರಗಿ' where id=23;
update states set state_name_k='ಬಾಬಾನಗರ' where id=24;
update states set state_name_k='ಘೊಣಸಗಿ' where id=25;
update states set state_name_k='ಅಳಗಿನಳ' where id=26;
update states set state_name_k='ಕಳ್ಳಕವಟಗಿ' where id=27;
update states set state_name_k='ಜಾಲಗೇರಿ' where id=28;
update states set state_name_k='ಯತ್ನಾಳ' where id=29;
update states set state_name_k='ಟಕ್ಕಳಕಿ' where id=30;
update states set state_name_k='ಹುಬನೂರ' where id=31;
update states set state_name_k='ಸಿದ್ದಾಪೂರ ಕೆ.' where id=32;
update states set state_name_k='ಧನರ್ಗಿ' where id=33;
update states set state_name_k='ಲೋಹಗಾಂವ' where id=34;
update states set state_name_k='ಇಟ್ಟಂಗಿಹಾಳ' where id=35;
update states set state_name_k='ಅರಕೇರಿ' where id=36;
update states set state_name_k='ಬರಟಗಿ' where id=37;
update states set state_name_k='ಹಂಚನಾಳ ಪಿ ಎಚ್' where id=38;
update states set state_name_k='ಬಬಲೇಶ್ವರ' where id=39;
update states set state_name_k='ಸಾರವಾಡ' where id=40;
update states set state_name_k='ಕಣಮುಚನಳ' where id=41;
update states set state_name_k='ದಾಶ್ಯಾಳ' where id=42;
update states set state_name_k='ಧನ್ಯಾಳ' where id=43;
update states set state_name_k='ಹೊನಗನಹಳ್ಳಿ' where id=44;
update states set state_name_k='ಸವನಳ್ಳಿ' where id=45;
update states set state_name_k='ತೊನಶ್ಯಾಳ' where id=46;
update states set state_name_k='ಕಾರಜೋಳ' where id=47;
update states set state_name_k='ದೂಡಿಹಾಳ' where id=48;
update states set state_name_k='ಕಾಖಂಡಕಿ' where id=49;
update states set state_name_k='ಹಲಗಣಿ' where id=50;
update states set state_name_k='ಯಕ್ಕುಂಡಿ' where id=51;
update states set state_name_k='ತಿಗಣಿಬಿದರಿ' where id=52;
update states set state_name_k='ಶೇಗುಣಸಿ' where id=53;
update states set state_name_k='ಮದಗುಣಕಿ' where id=54;
update states set state_name_k='ಕಂಬಾಗಿ' where id=55;
update states set state_name_k='ಅರ್ಜುಣಗಿ' where id=56;
update states set state_name_k='ಕುಮಠೆ' where id=57;
update states set state_name_k='ನಾಗರಾಳ' where id=58;
update states set state_name_k='ನಿಡೋಣಿ' where id=59;
update states set state_name_k='ಕಾತ್ರಾಳ' where id=60;
update states set state_name_k='ನಂದ್ಯಾಳ' where id=61;
update states set state_name_k='ಹೆಬ್ಬಾಳಟ್ಟಿ' where id=62;
update states set state_name_k='ಹೊಕ್ಕುಂಡಿ' where id=63;
update states set state_name_k='ಮಮದಾಪೂರ' where id=64;
update states set state_name_k='ಉಪ್ಪಲದಿನ್ನಿ' where id=65;
update states set state_name_k='ಮಂಗಳೂರ' where id=66;
update states set state_name_k='ಹಂಚನಾಳ ಪಿ ಎಮ್' where id=67;
update states set state_name_k='ಗುಣದಾಳ' where id=68;
update states set state_name_k='ಶಿರಬೂರ' where id=69;
update states set state_name_k='ಬಬಲಾದ' where id=70;
update states set state_name_k='ಬೊಳಚಿಕ್ಕಲಕಿ' where id=71;
update states set state_name_k='ದೇವರಗೆಣ್ಣೂರ ' where id=72;
update states set state_name_k='ಕೆಂಗಲಗುತ್ತಿ' where id=73;
update states set state_name_k='ದೇವಾಪುರ' where id=74;
update states set state_name_k='ಕೊಡಬಾಗಿ' where id=75;
update states set state_name_k='ತಾಜಪುರ P.M.' where id=76;
update states set state_name_k='ಸುತಗುಂಡಿ' where id=77;
update states set state_name_k='ಜೈನಾಪೂರ' where id=78;
update states set state_name_k='ಲಿಂಗದಳ್ಳಿ' where id=79;
update states set state_name_k='ಬೆಳ್ಳುಬ್ಬಿ' where id=80;
update states set state_name_k='ಹಂಗರಗಿ' where id=81;
update states set state_name_k='ಚಿಕ್ಕಗಲಗಲಿ' where id=82;
update states set state_name_k='ಜಂಬಗಿ H.' where id=83;
update states set state_name_k='ಹೊಸೂರ' where id=84;
update states set state_name_k='ಕಣಬೂರ' where id=85;
update states set state_name_k='ನಾಗಠಾಣ' where id=86;
update states set state_name_k='ಹುಣಶ್ಯಾಳ' where id=87;
update states set state_name_k='ಕನ್ನೂರ' where id=88;
update states set state_name_k='ಮಡಸನಾಳ' where id=89;
update states set state_name_k='ಜಂಬಗಿ A.' where id=90;
update states set state_name_k='ಹೊನ್ನಳ್ಳಿ' where id=91;
update states set state_name_k='ಅಲಿಯಾಬಾದ' where id=92;
update states set state_name_k='ಇಂಗನಾಳ' where id=93;
update states set state_name_k='ಗುಗದಡ್ಡಿ' where id=94;
update states set state_name_k='ಡೊಮನಾಳ' where id=95;
update states set state_name_k='ತಿಡಗುಂದಿ' where id=96;
update states set state_name_k='ಆಹೇರಿ' where id=97;
update states set state_name_k='ಮಖಣಾಪೂರ' where id=98;
update states set state_name_k='ಮಿಂಚನಾಳ' where id=99;
update states set state_name_k='ಬೊಮ್ಮನಹಳ್ಳಿ' where id=100;
update states set state_name_k='ಕನ್ನಾಳ' where id=101;
update states set state_name_k='ಗುಣಕಿ' where id=102;
update states set state_name_k='ಶಿರನಾಳ' where id=103;
update states set state_name_k='ದ್ಯಾಬೇರಿ' where id=104;
update states set state_name_k='ಮಹಲ ಬಾಗಾಯತ' where id=105;
update states set state_name_k='ಕಸಬಾ ವಿಜಯಪುರ' where id=106;
update states set state_name_k='ಹಡಗಲಿ' where id=107;
update states set state_name_k='ಕುಮಟಗಿ' where id=108;
update states set state_name_k='ಕಗ್ಗೋಡ' where id=109;
update states set state_name_k='ಶಿವಣಗಿ' where id=110;
update states set state_name_k='ಹೊನ್ನುಟಗಿ' where id=111;
update states set state_name_k='ಕವಲಗಿ' where id=112;
update states set state_name_k='ಹಿಟ್ಟಿನಹಳ್ಳಿ' where id=113;
update states set state_name_k='ಜುಮನಾಳ' where id=114;
update states set state_name_k='ಖತಿಜಾಪೂರ' where id=115;
update states set state_name_k='ಉತ್ನಾಳ' where id=116;
update states set state_name_k='ಹೆಗಡಿಹಾಳ' where id=117;
update states set state_name_k='ಕತಕನಳ್ಳಿ' where id=118;
update states set state_name_k='ಉಕುಮನಾಳ' where id=119;
update states set state_name_k='ಭೂತನಾಳ' where id=120;
update states set state_name_k='ಅಂಕಲಗಿ' where id=121;
update states set state_name_k='ಮಧಭಾವಿ' where id=122;
update states set state_name_k='ಐನಾಪೂರ' where id=123;
update states set state_name_k='ಬುರಣಾಪೂರ' where id=124;
update states set state_name_k='ರಂಬಾಪೂರ' where id=125;
update states set state_name_k='ತಿಕೋಟಾ' where id=126;
update states set state_name_k='ತೊರವಿ' where id=127;
update states set state_name_k='ತಾಜಪುರ H.' where id=128;
update states set state_name_k='ಕೋಟ್ಯಾಳ' where id=129;
update states set state_name_k='ಹೊನವಾಡ' where id=130;
update states set state_name_k='ಕನಮಡಿ' where id=131;
update states set state_name_k='ಬಿಜ್ಜರಗಿ' where id=132;
update states set state_name_k='ಬಾಬಾನಗರ' where id=133;
update states set state_name_k='ಘೊಣಸಗಿ' where id=134;
update states set state_name_k='ಜಾಲಗೇರಿ' where id=135;
update states set state_name_k='ಟಕ್ಕಳಕಿ' where id=136;
update states set state_name_k='ಸಿದ್ದಾಪೂರ ಕೆ.' where id=137;
update states set state_name_k='ಲೋಹಗಾಂವ' where id=138;
update states set state_name_k='ಅರಕೇರಿ' where id=139;
update states set state_name_k='ಬರಟಗಿ' where id=140;
update states set state_name_k='ಬಬಲೇಶ್ವರ' where id=141;
update states set state_name_k='ಸಾರವಾಡ' where id=142;
update states set state_name_k='ಹೊನಗನಹಳ್ಳಿ' where id=143;
update states set state_name_k='ಕಾರಜೋಳ' where id=144;
update states set state_name_k='ಕಾಖಂಡಕಿ' where id=145;
update states set state_name_k='ಹಲಗಣಿ' where id=146;
update states set state_name_k='ಅರ್ಜುಣಗಿ' where id=147;
update states set state_name_k='ನಿಡೋಣಿ' where id=148;
update states set state_name_k='ಕಂಬಾಗಿ' where id=149;
update states set state_name_k='ಕುಮಠೆ' where id=150;
update states set state_name_k='ಬೊಳಚಿಕ್ಕಲಕಿ' where id=151;
update states set state_name_k='ಮಮದಾಪೂರ' where id=152;
update states set state_name_k='ದೇವರಗೆಣ್ಣೂರ ' where id=153;
update states set state_name_k='ಗುಣದಾಳ' where id=154;
update states set state_name_k='ಜೈನಾಪೂರ' where id=155;
update states set state_name_k='ಹೊಸೂರ' where id=156;
update states set state_name_k='ನಾಗಠಾಣ' where id=157;
update states set state_name_k='ಕನ್ನೂರ' where id=158;
update states set state_name_k='ಜಂಬಗಿ A.' where id=159;
update states set state_name_k='ಅಲಿಯಾಬಾದ' where id=160;
update states set state_name_k='ತಿಡಗುಂದಿ' where id=161;
update states set state_name_k='ಆಹೇರಿ' where id=162;
update states set state_name_k='ಮಖಣಾಪೂರ' where id=163;
update states set state_name_k='ಗುಣಕಿ' where id=164;
update states set state_name_k='ವಿಜಯಪುರ' where id=165;
update states set state_name_k='ಹಡಗಲಿ' where id=166;
update states set state_name_k='ಕುಮಟಗಿ' where id=167;
update states set state_name_k='ಶಿವಣಗಿ' where id=168;
update states set state_name_k='ಹೊನ್ನುಟಗಿ' where id=169;
update states set state_name_k='ಮಧಭಾವಿ' where id=170;
update states set state_name_k='ಹಿಟ್ಟಿನಹಳ್ಳಿ' where id=171;
update states set state_name_k='ಜುಮನಾಳ' where id=172;
update states set state_name_k='ಹೆಗಡಿಹಾಳ' where id=173;
update states set state_name_k='ಐನಾಪೂರ' where id=174;
update states set state_name_k='ತಿಕೋಟಾ' where id=175;
update states set state_name_k='ತೊರವಿ' where id=176;
update states set state_name_k='ತಾಜಪುರ H.' where id=177;
update states set state_name_k='ಹೊನವಾಡ' where id=178;
update states set state_name_k='ಕನಮಡಿ' where id=179;
update states set state_name_k='ಬಿಜ್ಜರಗಿ' where id=180;
update states set state_name_k='ಸಿದ್ದಾಪೂರ ಕೆ.' where id=181;
update states set state_name_k='ಜಾಲಗೇರಿ' where id=182;
update states set state_name_k='ಅರಕೇರಿ' where id=183;
update states set state_name_k='ಬರಟಗಿ' where id=184;
update states set state_name_k='ಬಬಲೇಶ್ವರ' where id=185;
update states set state_name_k='ಸಾರವಾಡ' where id=186;
update states set state_name_k='ಜುಮನಾಳ' where id=187;
update states set state_name_k='ಕಾಖಂಡಕಿ' where id=188;
update states set state_name_k='ಹಲಗಣಿ' where id=189;
update states set state_name_k='ಅರ್ಜುಣಗಿ' where id=190;
update states set state_name_k='ಗುಣದಾಳ' where id=191;
update states set state_name_k='ನಿಡೋಣಿ' where id=192;
update states set state_name_k='ಮಮದಾಪೂರ' where id=193;
update states set state_name_k='ಹೊಸೂರ' where id=194;
update states set state_name_k='ದೇವರಗೆಣ್ಣೂರ ' where id=195;
update states set state_name_k='ಜೈನಾಪೂರ' where id=196;
update states set state_name_k='ನಾಗಠಾಣ' where id=197;
update states set state_name_k='ಕನ್ನೂರ' where id=198;
update states set state_name_k='ಜಂಬಗಿ A.' where id=199;
update states set state_name_k='ಅಲಿಯಾಬಾದ' where id=200;
update states set state_name_k='ಮಖಣಾಪೂರ' where id=201;
update states set state_name_k='ಆಹೇರಿ (ಭೇರಿ)' where id=202;
update states set state_name_k='ಗುಣಕಿ' where id=203;
update states set state_name_k='ವಿಜಯಪುರ (CMC+)' where id=204;
update states set state_name_k='ಹೊನ್ನುಟಗಿ' where id=205;
update states set state_name_k='ಶಿವಣಗಿ' where id=206;
update states set state_name_k='ಹಿಟ್ಟಿನಹಳ್ಳಿ' where id=207;
update states set state_name_k='ಮಧಭಾವಿ' where id=208;
update states set state_name_k='ತಿಕೋಟಾ' where id=209;
update states set state_name_k='ಬಬಲೇಶ್ವರ' where id=210;
update states set state_name_k='ಹೊನವಾಡ' where id=211;
update states set state_name_k='ಅರಕೇರಿ' where id=212;
update states set state_name_k='ನಾಗಠಾಣ' where id=213;
update states set state_name_k='ಸಾರವಾಡ' where id=214;
update states set state_name_k='ಕಾಖಂಡಕಿ' where id=215;
update states set state_name_k='ಮಮದಾಪೂರ' where id=216;
update states set state_name_k='ಶಿವಣಗಿ' where id=217;
update states set state_name_k='ವಿಜಯಪುರ (CM)' where id=218;
